# Generated by Django 5.0 on 2024-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('api_hash', models.CharField(max_length=200)),
                ('app_name', models.CharField(default='Corporate Telegram Manager', max_length=100)),
                ('app_version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'global_app_settings',
                'verbose_name': 'Global App Settings',
                'verbose_name_plural': 'Global App Settings',
            },
        ),
        migrations.CreateModel(
            name='ProxyServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=200)),
                ('port', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('proxy_type', models.CharField(choices=[('socks5', 'SOCKS5'), ('http', 'HTTP'), ('mtproto', 'MTProto')], default='socks5', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proxy_servers',
                'verbose_name': 'Proxy Server',
                'verbose_name_plural': 'Proxy Servers',
            },
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_fio', models.CharField(blank=True, max_length=200, null=True)),
                ('account_note', models.TextField(blank=True, null=True)),
                ('encrypted_api_id', models.BinaryField(blank=True, null=True)),
                ('encrypted_api_hash', models.BinaryField(blank=True, null=True)),
                ('encrypted_session', models.BinaryField(blank=True, null=True)),
                ('encrypted_recovery_email', models.BinaryField(blank=True, null=True)),
                ('encrypted_phone_code_hash', models.BinaryField(blank=True, null=True)),
                ('session_updated_at', models.DateTimeField(blank=True, null=True)),
                ('session_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('account_status', models.CharField(choices=[('pending', 'Pending'), ('pending_2fa', 'Pending 2FA'), ('pending_reauthorization', 'Pending Reauthorization'), ('active', 'Active'), ('suspended', 'Suspended'), ('reclaimed', 'Reclaimed'), ('dead', 'Dead'), ('flood', 'Flood Wait')], default='pending', max_length=30)),
                ('last_ping', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('activity_status', models.CharField(choices=[('active', 'Active'), ('dead', 'Dead'), ('flood', 'Flood')], default='active', max_length=20, verbose_name='Статус активности')),
                ('device_params', models.JSONField(blank=True, default=dict, null=True, verbose_name='Параметры устройства')),
                ('encryption_version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.proxyserver', verbose_name='Прокси-сервер')),
            ],
            options={
                'db_table': 'telegram_accounts',
            },
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('check_account', 'Проверка аккаунта'), ('bulk_check', 'Групповая проверка'), ('reauthorize', 'Повторная авторизация'), ('reclaim', 'Возврат аккаунта')], max_length=50)),
                ('account_ids', models.JSONField(blank=True, help_text='ID аккаунтов для групповой операции', null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В процессе'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Прогресс в процентах')),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.telegramaccount')),
            ],
            options={
                'db_table': 'task_queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('action_details', models.JSONField(blank=True, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.telegramaccount')),
            ],
            options={
                'db_table': 'account_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['phone_number'], name='telegram_ac_phone_n_8c0f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['account_status'], name='telegram_ac_account__0c8b46_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['employee_id'], name='telegram_ac_employe_8b6a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['employee_fio'], name='telegram_ac_employe_5e7c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['last_ping'], name='telegram_ac_last_pi_07df22_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['activity_status'], name='telegram_ac_activit_9d5c17_idx'),
        ),
        migrations.AddIndex(
            model_name='taskqueue',
            index=models.Index(fields=['status'], name='task_queue_status_ca3c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskqueue',
            index=models.Index(fields=['task_type'], name='task_queue_task_ty_0f3b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskqueue',
            index=models.Index(fields=['created_at'], name='task_queue_created_c0b219_idx'),
        ),
        migrations.AddIndex(
            model_name='accountauditlog',
            index=models.Index(fields=['account_id'], name='account_aud_account_2c61a1_idx'),
        ),
    ]
