# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('api_hash', models.CharField(max_length=200)),
                ('app_name', models.CharField(default='Corporate Telegram Manager', max_length=100)),
                ('app_version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'global_app_settings',
                'verbose_name': 'Global App Settings',
                'verbose_name_plural': 'Global App Settings',
            },
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_fio', models.CharField(blank=True, max_length=200, null=True)),
                ('account_note', models.TextField(blank=True, null=True)),
                ('encrypted_api_id', models.BinaryField()),
                ('encrypted_api_hash', models.BinaryField()),
                ('encrypted_session', models.BinaryField()),
                ('encrypted_recovery_email', models.BinaryField()),
                ('session_updated_at', models.DateTimeField()),
                ('session_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('reclaimed', 'Reclaimed')], default='active', max_length=20)),
                ('encryption_version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telegram_accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('action_details', models.JSONField(blank=True, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.telegramaccount')),
            ],
            options={
                'db_table': 'account_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['phone_number'], name='idx_telegram_accounts_phone'),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['account_status'], name='idx_telegram_accounts_status'),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['employee_id'], name='idx_telegram_accounts_employee'),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['employee_fio'], name='idx_telegram_accounts_employee_fio'),
        ),
    ]
