# Generated by Django 5.1.15 on 2026-01-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_triggerevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggerevent',
            name='account',
        ),
        migrations.RenameIndex(
            model_name='telegramaccount',
            new_name='telegram_ac_phone_n_ff3550_idx',
            old_name='idx_telegram_accounts_phone',
        ),
        migrations.RenameIndex(
            model_name='telegramaccount',
            new_name='telegram_ac_account_4736f6_idx',
            old_name='idx_telegram_accounts_status',
        ),
        migrations.RenameIndex(
            model_name='telegramaccount',
            new_name='telegram_ac_employe_eba073_idx',
            old_name='idx_telegram_accounts_employee',
        ),
        migrations.RenameIndex(
            model_name='telegramaccount',
            new_name='telegram_ac_employe_ee8ab8_idx',
            old_name='idx_telegram_accounts_employee_fio',
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='encrypted_phone_code_hash',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('reclaimed', 'Reclaimed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='encrypted_api_hash',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='encrypted_api_id',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='encrypted_recovery_email',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='encrypted_session',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='session_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TriggerEvent',
        ),
    ]
