# Generated by Django 5.1.15 on 2026-01-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_triggerevent_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_2fa', 'Pending 2FA'), ('pending_reauthorization', 'Pending Reauthorization'), ('active', 'Active'), ('suspended', 'Suspended'), ('reclaimed', 'Reclaimed')], default='pending', max_length=30),
        ),
    ]
