# Generated by Django 5.1.15 on 2026-01-19 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_telegramaccount_account_status'),
    ]

    operations = [
        # УДАЛЕНИЕ: ProxyServer, TaskQueue уже созданы в 0001_initial.py
        # Эти модели не должны создаваться повторно
        
        # Добавляем поля к TelegramAccount
        migrations.AddField(
            model_name='telegramaccount',
            name='activity_status',
            field=models.CharField(choices=[('active', 'Active'), ('dead', 'Dead'), ('flood', 'Flood')], default='active', max_length=20, verbose_name='Статус активности'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='device_params',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Параметры устройства'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_2fa', 'Pending 2FA'), ('pending_reauthorization', 'Pending Reauthorization'), ('active', 'Active'), ('suspended', 'Suspended'), ('reclaimed', 'Reclaimed'), ('dead', 'Dead'), ('flood', 'Flood Wait')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.proxyserver', verbose_name='Прокси-сервер'),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['last_ping'], name='telegram_ac_last_pi_03925a_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['activity_status'], name='telegram_ac_activit_1e5b7e_idx'),
        ),
        # УДАЛЕНИЕ: Поле account уже добавлено в 0001_initial.py
        # migrations.AddField(
        #     model_name='taskqueue',
        #     name='account',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.telegramaccount'),
        # ),
        # УДАЛЕНИЕ: Индексы уже добавлены в 0001_initial.py
        # migrations.AddIndex(
        #     model_name='taskqueue',
        #     index=models.Index(fields=['status'], name='task_queue_status_70f75a_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='taskqueue',
        #     index=models.Index(fields=['task_type'], name='task_queue_task_ty_d8a6cb_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='taskqueue',
        #     index=models.Index(fields=['created_at'], name='task_queue_created_9029ec_idx'),
        # ),
    ]
